### ISSUE TITLE
Responsive Design on all Pages

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#1]
For better support on mobile browsers and chromebooks, make sure all pages look good with smaller screens

- [x] Home
- [x] Search
- [x] Privacy Policy
- [ ] My Sets
- [x] Admin Portal
- [ ] Leaderboard
- [x] Set Detail
- [ ] Flashcards
- [ ] Learn
- [ ] Test
- [ ] Match
- [ ] Set Editor

@DG3QRT1 @Nikhilatvocabustudy Can you go through each of these pages and make sure they look good? If there's some serious work to be done, create a new issue. Thank you!

**Comment by grimsteel** [comment]
@DG3QRT1 @Nikhilatvocabustudy @IMGROOT2 please...

**Comment by DG3QRT1** [comment]
On a chromebook or phone? I can do chromebook, but not very small screens like phones

**Comment by grimsteel** [comment]
You can use the device toolbar in Chrome - `Ctrl + Shift + M` in the developer tools (Choose something like an iphone 12 in the dimensions dropdown at the top) Honestly phones these days are way too small

**Comment by DG3QRT1** [comment]
Footer overflows

**Comment by DG3QRT1** [comment]
The Browse sets/ heading at the top of the page does not scale, and the flaschards overflow (text too big)

**Comment by DG3QRT1** [comment]
The text sizes are just not right overall on small screens

**Comment by ShreyanKhanna** [comment]
> Footer overflows

yea the footer overflows, so I'm thinking that if we are able to know the size of the device or just the device that vocabustudy is on, then we can resize everything so that no overflow doesn't happen.
Also are we able to search for users on vocabustudy right now or not, and if yes, how do I do that?

**Comment by grimsteel** [comment]
Searching for users is not possible without the Firebase Admin SDK...

**Comment by ShreyanKhanna** [comment]
Ok so can we just make another search bar just for users? Or is that not possible either

**Comment by grimsteel** [comment]
Searching for users isn't possible on the client

**Comment by grimsteel** [comment]
So no

**Comment by ShreyanKhanna** [comment]
Alr … so do we just want to keep that feature away and not have it for vocabustudy or if possible keep it for 2.0.0

**Comment by ShreyanKhanna** [comment]
Also another thing for design… can we make users be allowed to change designs or is it too much work/ you want to keep it the way it is rn

**Comment by ShreyanKhanna** [comment]
@grimsteel

**Comment by IMGROOT2** [comment]
> Also another thing for design… can we make users be allowed to change designs or is it too much work/ you want to keep it the way it is rn

it's definitely possible, but it'll diverge from working on core features. can we move that into #191?

> Alr … so do we just want to keep that feature away and not have it for vocabustudy or if possible keep it for 2.0.0

That goes to future; we can't just "do it", I think we either need a lot of Firebase modifications (like admin SDK that @grimsteel was talking about), or maybe even bigger servers. btw, we're broke LOL

**Comment by grimsteel** [comment]
> I think we either need a lot of Firebase modifications (like admin SDK that @grimsteel was talking about)

Cloud Functions + Admin SDK = Callable API that can fetch all users
Cloud Functions is free for a certain amount of requests but requires the blaze plan

**Comment by ShreyanKhanna** [comment]
Oh gotcha

**Comment by IMGROOT2** [comment]
how does a nonprofit... crowdfund... with an audience of middle schoolers LOL

**Comment by IMGROOT2** [comment]
![image](https://user-images.githubusercontent.com/116324098/201815782-8140d40d-81d3-4af8-99bc-1e19025ba983.png)
yeah lol

**Comment by grimsteel** [comment]
> The text sizes are just not right overall on small screens

@DG3QRT1 Do you have any specific examples? The text generally shouldn't _scale_

**Comment by grimsteel** [comment]
This is pretty much done due to Bulma
