### ISSUE TITLE
Timelines

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#142]
Add study guides to help people study for tests/quizzes
They could cover a subject
Special Types:
* Timeline
  - [x] Editor UI
  - [x] Viewer UI
  - [ ] Special study modes for timeline (dates, which event was this, etc)

**Comment by IMGROOT2** [comment]
> Add study guides to help people study for tests/quizzes
> They could cover a subject

do you mean an online view-only free database containing pictures of study guides given out in class? that doesn't seem bad

**Comment by grimsteel** [comment]
Closing as completed as popular opinion shows that most people won't benefit from extra study modes
