### ISSUE TITLE
Migrate to Firestore REST api, controlled in Service Worker

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#144]
Provide a quick wrapper for the firestore rest api in the service worker, will greatly reduce bundle sizes

**Comment by IMGROOT2** [comment]
I need a lot of time to understand what REST API is, let alone make a wrapper lol. Can someone else who knows what they're doing get this done?

**Comment by grimsteel** [comment]
I planned to do it today

**Comment by grimsteel** [comment]
**R**easonable **E**ggs for **S**upper **T**omorrow

**Comment by IMGROOT2** [comment]
ohhhh i get it now

**Comment by ShreyanKhanna** [comment]
> ohhhh i get it now

I don’t but good for u ig… also I love the new logo.. are we going to integrate that into the website, if yes… is it already done?

**Comment by IMGROOT2** [comment]
> I don’t but good for u ig… 

sarcasm lol. i have no clue 

> also I love the new logo..

ty! i designed it and please answer the poll in discord haha

> are we going to integrate that into the website, if yes… is it already done?

ofc and siddhant did it alr i think

**Comment by ShreyanKhanna** [comment]
HAHAHAHAH MB MB 

okay cool is that our favicon now .. actually I could just check this myself

**Comment by IMGROOT2** [comment]
you kinda can't unless you emulate bc we haven't released

**Comment by ShreyanKhanna** [comment]
Oh okay

**Comment by grimsteel** [comment]
Sorry about the delay - I had to set up the webmanifest
@IMGROOT2 if you could give me the same icon but with a + instead of a V for a PWA Shortcut that would be great

**Comment by IMGROOT2** [comment]
> Sorry about the delay - I had to set up the webmanifest @IMGROOT2 if you could give me the same icon but with a + instead of a V for a PWA Shortcut that would be great

Did I end up giving it to you?

**Comment by grimsteel** [comment]
You did
![shortcut add 96](https://github.com/For-0/vocabustudy/raw/467daddda447843ba86062ed1e4b172037445985/src/icons/shortcut-add-96.png)

**Comment by grimsteel** [comment]
Speaking of shortcuts, I need to update parcel
