### ISSUE TITLE
Notifications for social interactions

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#152]
Notify the user in vocabustudy or by email if someone likes/comments on your set

**Comment by Nikhilatvocabustudy** [comment]
This brings me to another thing, could we create a vocabustduy maillingl ist? Since a lot of people aren't on the discord, and discord is just not very convenient

**Comment by Nikhilatvocabustudy** [comment]
Only issue is many people will use school emails

**Comment by Nikhilatvocabustudy** [comment]
Now next year we can, since we can email our peers

**Comment by Nikhilatvocabustudy** [comment]
let me know if I should report this as a suggestion or not.

**Comment by ShreyanKhanna** [comment]
> This brings me to another thing, could we create a vocabustduy maillingl ist? Since a lot of people aren't on the discord, and discord is just not very convenient

wait wdym a mailing list

**Comment by ShreyanKhanna** [comment]
like a signup for updates?

**Comment by Nikhilatvocabustudy** [comment]
yea pretty much, you get the changelog in your email

**Comment by ShreyanKhanna** [comment]
thats a good idea ,def make this as a suggestion

> yea pretty much, you get the changelog in your email
