### ISSUE TITLE
Study Guides/Online Notes

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#154]
In an effort to make Vocabustudy help people more with learning bigger concepts, add something where they can study notes for upcoming tests in a form where they can also do practice problems

It could support styling with markdown

**Comment by IMGROOT2** [comment]
@grimsteel Do you mean like OneNote but for notes and built-in? We can make it an "online note hub", where you could add images that could be your paper notes, so everything is in one place.

but we'd have to add space to firebase, and it would take a long time to code
![image](https://user-images.githubusercontent.com/116324098/197321802-5b755562-e7e0-4ae3-9b1b-fb8688d5c779.png)

^^
PRESENTING: ACTUAL WORK DONE BY RUHAN!!! YAY!!!

**Comment by grimsteel** [comment]
Wow that diagram is really good. (If you could do it for other features that come in that would be great)
That's pretty much what I was thinking, but with some slight changes
I was thinking the editor could be kind of like this:
![image](https://user-images.githubusercontent.com/115331356/197352457-e8199b47-db9d-4f4d-b296-4ed0fe1d4fd2.png)
(You can access it by clicking + New Study Guide on nightly - https://vocabustudyonline--nightly-q9kbiq6r.web.app/)

In the editor, you will be able to add "Learn" sections, in which it's just text/images like in your diagram. I'm thinking, for simplicity, you just edit with markdown. Later, we can add a toolbar at the top (bold/italic/font size/styling) that just does common markdown things for you like Github's one
You can also add "Quiz" sections, where you can create a couple questions to help people who are viewing your study guide practice

The viewer could be something like Khan Academy, where you can select learn/quiz sections on one side, and the big area in the center updates.

Now as for images, that's a pretty significant problem. Rn, you can insert images if you have the link to them. I'm holding off on using Cloud Storage for uploaded files, because I feel I would hit the free plan limit pretty quickly. Hopefully people can find some place to upload their files. (Google drive? I could probably put in a manual hack to convert google drive share links to actual embeds - I feel like I did that somewhere)

I don't really like the concept of autosaving because while it is useful, it means a lot more writes to the database. Right now, I just put a warning if you try to exit without saving

Now I like the concept of showing your study guides across the top, so you can change them quickly. While that would mean more database reads, I think I could order by last modified, limit by something like 3. The Firestore JS sdk does not natively support ordering by last modified, but the REST api does. I'm anyway planning to migrate to just using the REST api to reduce bundle sizes

Finally, I want to interlink the viewer and editor UIs - so people can edit sets easily from the viewer page. I also want to make the UIs for editing/viewing much more similar to provide a smoother flow

**Comment by IMGROOT2** [comment]
I just checked nightly; it looks really good. However, just some design changes would make it look even better. 

Right now, it looks too much like a vocab set when you exit out of editing. If we put the tabs at the top, it would seem more comprehensive and useful. Also, I think the text boxes are too small to view full study guides.

I agree with everything else you said. it looks really good!

**Comment by grimsteel** [comment]
> just some design changes would make it look even better

We need to change the design of the whole site lol
Quizlet's editor ui is way better

> Right now, it looks too much like a vocab set when you exit out of editing

Are you talking about how the set shows up in the My Sets/Search page or the Guide Viewing page (/guide/<id>/view/)?
Either way, I do think it looks too similar

> If we put the tabs at the top

There aren't any tabs yet... 
However I am planning to put them at the top

> the text boxes
The ones in the set editor or the set viewer? The ones in the set viewer are quite big - they will expand to fit (https://vocabustudyonline--nightly-q9kbiq6r.web.app/guide/zvev9SGZrjM9UdYiJiy7/view/)

Also I had no idea Jamestown was so long ago
![image](https://user-images.githubusercontent.com/115331356/197356805-89e0d145-adde-4853-9d41-a629b5a6ea89.png)

**Comment by IMGROOT2** [comment]
Set editor is too small
![image](https://user-images.githubusercontent.com/116324098/197358015-376be7c4-a9cb-4da4-aeb1-86023f2c46db.png)

>We need to change the design of the whole site lol
>Quizlet's editor ui is way better

I can try changing up the CSS to make it look better, we'll see

> Also I had no idea Jamestown was so long ago

1. LOL mistype, I didn't care to correct
2. how can you see my guide when it's private 😨 lol

**Comment by IMGROOT2** [comment]
Also, what's your idea behind having multiple guide items? i thought it was gonna be a notes hub, but clearly you mean something different

**Comment by grimsteel** [comment]
> Set editor is too small

Agreed, I will change it when I add Quizzes later today

> I can try changing up the CSS to make it look better, we'll see

Yes, mainly rearrange the different things to make the set viewer and the set editor look more similar

> how can you see my guide when it's private 😨

😈

> what's your idea behind having multiple guide items?

kind of like Khan Academy, where there are multiple articles and multiple practices regarding a single topic. Apparently Michael saw the study guides feature and decided to make a set for that:
![image](https://user-images.githubusercontent.com/115331356/197358177-42b3e527-c8b6-4ef4-ae96-06bf72e38588.png)
Sometimes I get the feeling he is *trying* to find something wrong with Vocabustudy

> i thought it was gonna be a notes hub

Kind of?

**Comment by grimsteel** [comment]
> Michael saw the study guides feature and decided to make a set for that:

The screenshot I sent is an early implementation - the final implementation will only show one section at a time, you can switch between them with the tabs

I created an issue and branch for you to work on this
