### ISSUE TITLE
Rearrange elements for a better UI flow

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#166]
**Is your feature request related to a problem? Please describe.**
It's confusing when the editor and viewer uis are different

**Describe the solution you'd like**
Rearrange elements to make the look similar. If you are the creator, put a link to the editor in the viewer ui

In addition, just improve the styling of the overall website as a whole

- [ ] Make editor and viewer look similar
- [ ] Cross link them
- [x] Improve styling of whole website

**Comment by grimsteel** [comment]
@IMGROOT2 If you could commit to the branch for this issue (`166-rearrange-elements-to-for-a-better-ui-flow`) instead of directly to main that would be great

In the future, any big changes like this should go in their own branch. We can then make a Pull Request

**Comment by grimsteel** [comment]
Oops idk why I typed "to for a better UI flow"

**Comment by IMGROOT2** [comment]
> @IMGROOT2 If you could commit to the branch for this issue (`166-rearrange-elements-to-for-a-better-ui-flow`) instead of directly to main that would be great
> 
> In the future, any big changes like this should go in their own branch. We can then make a Pull Request

sure!

**Comment by grimsteel** [comment]
Thanks! I'm going to put some background on the build tools in the Vocabustudy Developers team
