### ISSUE TITLE
Add nightly link on stable

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#194]

**Comment by IMGROOT2** [comment]
I've added the nightly link... on the soon-to-be nightly. LOL!

but I committed the change to main

https://github.com/For-0/vocabustudy/commit/c05e1b16930576a4dcd251a75e0ba2134ad3ad7a

**Comment by IMGROOT2** [comment]
aand its merged

**Comment by grimsteel** [comment]
Thanks!
Seems like I removed the leaderboard at about the same time, so my client did merged the diverged branches.

BTW you can put something like Fixes #194 in your commit messages to auto close the issues

**Comment by IMGROOT2** [comment]
> Thanks! Seems like I removed the leaderboard at about the same time, so my client did merged the diverged branches.

I saw! Nice.

> BTW you can put something like Fixes #194 in your commit messages to auto close the issues

haha, I also saw that. i didn't know it autoclosed issues, though. thanks!
