### ISSUE TITLE
Omkar's Locker Number: add to Donations page

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#198]
@DG3QRT1 we need your locker number

**Comment by DG3QRT1** [comment]
There is no locker number I removed it

**Comment by IMGROOT2** [comment]
@DG3QRT1 omkar said he's "going to change that". i think he's gonna make a sign. I'll open another issue that's more specific

**Comment by DG3QRT1** [comment]
> 

Siddhant is going to print it but his printer ran out of ink

This is not an error
We know that we have to do it

**Comment by IMGROOT2** [comment]
i have a color printer- i can print it and give it to omkar on Monday. i just need the file

**Comment by grimsteel** [comment]
Sure, that would be great
It's a Google Drawing - I shared it with your student account
