### ISSUE TITLE
Include footer on homepage

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#199]
it'll be easier to access the discord server, nightly URL (I'm adding that) #194, etc.

**Comment by grimsteel** [comment]
The homepage is supposed to be a kind of flat design but sure I'll find a way

**Comment by IMGROOT2** [comment]
sure, obv your choice. i just feel like putting privacy policy, etc. on home page would be practical.

![image](https://user-images.githubusercontent.com/116324098/198164075-62a9bb52-77b6-40fe-8d9d-cda613dc0892.png)

I love github's footer bar, it's really simplistic and looks nice. and, you can find it almost everywhere

**Comment by grimsteel** [comment]
> sure, obv your choice. i just feel like putting privacy policy, etc. on home page would be practical.

Sure I'll do it
