### ISSUE TITLE
Michael's vocab set single-handedly crashes Vocabustudy

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#214]
https://vocabustudyonline.web.app/set/ZEAuZPbTS5JlB1goITO5/view/

![image](https://user-images.githubusercontent.com/116324098/199630009-60267ce8-7820-4025-835f-5ad29873fd68.png)

just bright red. and all I wanted was to study the bill of rights ;(

**Comment by grimsteel** [comment]
Works as intended
