### ISSUE TITLE
Set leads to 404

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#215]
“Official - Bill of Rights” by “- Ruhan -“ leads to a 404 error when clicked on to view.

**Comment by IMGROOT2** [comment]
https://vocabustudyonline.web.app/set/P7UrXFbf6ALDb8FsKnGj/view/

**Comment by grimsteel** [comment]
It doesn't...

**Comment by grimsteel** [comment]
Can you send a stack trace? Does it occur on nightly or normal?

**Comment by IMGROOT2** [comment]
I’ll do it later. Normal
