### ISSUE TITLE
Re-add Bug reporting leaderboard link

### ISSUE THREAD

**Issue by DG3QRT1** [For-0/vocabustudy#220]
Re-add bug reporting leaderboard link in footer
I will do this

**Comment by grimsteel** [comment]
Make sure to add an icon and a link. (Ruhan forgot to do this for the donate link so you can do that too)

**Comment by DG3QRT1** [comment]
ok

**Comment by DG3QRT1** [comment]
> Make sure to add an icon and a link. (Ruhan forgot to do this for the donate link so you can do that too)

No? There is an icon and a link for donate. I did this (I added the donate link and the icon) a long time ago.

**Comment by grimsteel** [comment]
my memory is slowly breaking down

either that or history is doing something

**Comment by grimsteel** [comment]
Sorry I meant the Nightly Build link (he forgot to add an icon)
