### ISSUE TITLE
Discord widget

### ISSUE THREAD

**Issue by DG3QRT1** [For-0/vocabustudy#228]
Discord widget

**Comment by IMGROOT2** [comment]
@DG3QRT1 i thought we weren’t going to add a discord widget…?

**Comment by IMGROOT2** [comment]
You put it into changelog in discord but 0.6.7 was already released, and you didn’t commit anything other than Grammar. I’m lost right now

**Comment by grimsteel** [comment]
That _is_ true... it says "Reported and fixed by Omkar"

**Comment by grimsteel** [comment]
> @DG3QRT1 i thought we weren’t going to add a discord widget…?

We weren't...

**Comment by grimsteel** [comment]
I think what happened is that he was going to add one, but then I told him not to

**Comment by IMGROOT2** [comment]
Oh so he just closed the issue, got it
