### ISSUE TITLE
Add "verified" text on My Account

### ISSUE THREAD

**Issue by DG3QRT1** [For-0/vocabustudy#235]
On the My Account page, 
When your account is not verified, it says "not verified" in red.
However, when your account is verified, it does not say anything.
This is not very important, but add green "verified" when verified
Anyone can do this (me, Ruhan , Siddhant)

**Comment by ShreyanKhanna** [comment]
Or me lmaooo

**Comment by IMGROOT2** [comment]
I'll get this done

**Comment by grimsteel** [comment]
Ok I fixed this in 0824584
