### ISSUE TITLE
Global Tags

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#240]
Vocabustudy Tags

Vocabustudy Tags are identifiers that appear everywhere, which help differentiate people from others: 
![image](https://user-images.githubusercontent.com/116324098/202097307-329786b8-5702-4b69-8571-3c403a4b3858.png)
It's really messy, lol.

Tags can be implemented as an array, where every user has a binary array ([0,1,1,0,0,0,0]). 1 means they have the tag; 0 means they don't. We add more values for the more tags we have. This is stored in Firebase.

Types of tags (can add more later):

- Dev -> Developer of Vocabustudy. Must be in Vocabustudy-Developers Organization Team.
- For Zero -> Co-founders only, right now. Maybe if we have people in important roles in the nonprofit, we'll give them the For Zero tag.
- Donator -> Made a donation. For now, we'll manually update, but we can automate this later on
- Honor -> Includes important test accounts, staff in discord, GitHub contributors, yk. A lot of people will have this role.
- Helper -> Helpers in the Discord server. These are trustworthy people who make good sets. Only obtainable through applications sent through Discord.
- number 1 Bugger -> Submitted the most bugs (obv Michael I think)
- number 1 Active -> Most active person on vocabustudy (idk how to do this) **(Only an normal user may get this role)**
- number 1 Set Maker -> Creator of most sets **(Only an normal user may get this role)**

Special Roles:

New Member -> Only given for the first 7 days of getting new role.
"Verified" Checkmark -> Given to only Siddhant, Ruhan, Omkar, and Nikhil's accounts

All of this will take a good amount of time to implement, which is why I'm setting the milestone to 2.0.0. Please let me know what modifications we should make

**Comment by ShreyanKhanna** [comment]
Cool, with this I also thought of like friends and follow buttons for users to know when their friends are making sets

**Comment by ShreyanKhanna** [comment]
I can also help with this if needed

**Comment by ShreyanKhanna** [comment]
Also what is the vocabustudy devoeloper team? Am
I in that?

**Comment by grimsteel** [comment]
This will be pretty hard to implement - Firebase does not offer a method for querying a specific user's roles w/o the Admin SDK

> New Member -> Only given for the first 7 days of getting new role.
> "Verified" Checkmark -> Given to only Siddhant, Ruhan, Omkar, and Nikhil's accounts

No to both of these - New Member is too hard to implement ("First 7 days") and Verified is redundant

**Comment by grimsteel** [comment]
Instead of Custom Claims, we could make another thing in the database
Or we could do cloud storage because it will be cached for a pretty long amount of time but the SDK is wayyyyy too big

**Comment by grimsteel** [comment]
I just saw this:

> where every user has a binary array ([0,1,1,0,0,0,0]).

I have something even better - binary flags! (Or is that what you were thinking about?)
Let's say the number is 0110000 - that represents the same thing as the array
In decimal, that's 48 so we just store 48 in the database!

**Comment by ShreyanKhanna** [comment]
So binary is better tight

**Comment by grimsteel** [comment]
> Yea but there is multiple ways to get 48

No there's only one way

**Comment by ShreyanKhanna** [comment]
Oh wait

**Comment by ShreyanKhanna** [comment]
I’m selling

**Comment by ShreyanKhanna** [comment]
Nevermind

**Comment by IMGROOT2** [comment]
> I have something even better - binary flags! (Or is that what you were thinking about?) Let's say the number is 0110000 - that represents the same thing as the array In decimal, that's 48 so we just store 48 in the database!

That's genius!! perfect

**Comment by grimsteel** [comment]
Thanks! So let's say `0100000` (32) means "Admin", `0010000` (16) means "Honor" and `0001000` (8) means "Helper"
```js
Boolean(48 & 32) // true
Boolean(48 & 16) // true
Boolean(48 & 8) // false
```

We can probably store all of this in Cloud Storage as a JSON file (the tags won't change too often right?) with a 2-3 day cache
```jsonc
{
  // The bit mask is  2^index in array
  "t": [{"n": "Dev", "c": "some color"},{"n": "For Zero", "c": "some color"},{"n": "Donator", "c": "some color"},{"n": "Honor", "c": "some color"},{"n": "Helper", "c": "some color"}],
  "u": {"userid": 48, "userid2": 10}
}
```

Then to parse it:
```js
const globalTags = await fetch("...");
function getTagsForUser(userId) {
  let userTags = [];
  let userTagsNum = globalTags.u[userId];
  for (let [i, tag] of globalTags.t.entries()) {
    if (userTagsNum & (1 << 5)) userTags.push(tag);
  }
  return userTags;
}
```

**Comment by DG3QRT1** [comment]
Good idea

**Comment by ShreyanKhanna** [comment]
> Thanks! So let's say `0100000` (32) means "Admin", `0010000` (16) means "Honor" and `0001000` (8) means "Helper"
> 
> ```js
> Boolean(48 & 32) // true
> Boolean(48 & 16) // true
> Boolean(48 & 8) // false
> ```
> 
> We can probably store all of this in Cloud Storage as a JSON file (the tags won't change too often right?) with a 2-3 day cache
> 
> ```js
> {
>   // The bit mask is  2^index in array
>   "t": [{"n": "Dev", "c": "some color"},{"n": "For Zero", "c": "some color"},{"n": "Donator", "c": "some color"},{"n": "Honor", "c": "some color"},{"n": "Helper", "c": "some color"}],
>   "u": {"userid": 48, "userid2": 10}
> }
> ```
> 
> Then to parse it:
> 
> ```js
> const globalTags = await fetch("...");
> function getTagsForUser(userId) {
>   let userTags = [];
>   let userTagsNum = globalTags.u[userId];
>   for (let [i, tag] of globalTags.t.entries()) {
>     if (userTagsNum & (1 << 5)) userTags.push(tag);
>   }
>   return userTags;
> }
> ```

Ok that is acc perfect… idk why ur code looks so much better than mine… but yea genius

**Comment by grimsteel** [comment]
I love binary operations

**Comment by IMGROOT2** [comment]
Your code seems great. Although, because of the number 1 tags, it will be better to use a 1 day cache so it updates every day.

**Comment by IMGROOT2** [comment]
> I love binary operations

I can see that, lol. Will the JSON file be automatically updated? does Firebase take care of that?

**Comment by grimsteel** [comment]
I don't think there would be a source to automatically update from, so we would have to do it manually
Also I'm not sure if we should have the #1 tags - that encourages competition (trust me people have been telling me to bring the leaderboard back...) which I don't want

**Comment by IMGROOT2** [comment]
firestore is a source to automatically update from, no? we assign the binary code to each uid. can we not fetch the binary number whenever we need to display tags, and then write a function to display them?

**Comment by grimsteel** [comment]
There are three possible things we could do:
1. Use Firestore and generate a JSON stored in Cloud Storage
2. Do it all in Cloud Storage (my preferred option)
3. Do it all in Firestore (I think this is what you are saying?)

The thing about option 3 is that it would be harder to cache than Cloud Storage. In addition, there are two possible options for that:
`users` collection:

| ID | tags | <other acct preferences (#191)> |
| - | - | - |
| uid1 | 48 | stuff |
| uid2 | 36 | more stuff |

`tags` collection:

| ID | tags |
| - | - |
| random thing because there will only be one document here | `{"uid1": 48, "uid2": 36}` |

the `users` collection would mean one DB read for each user (too much even w/ caching)
the `tags` collection is reinventing cloud storage
I can write a script to update the JSON file at our wish

**Comment by ShreyanKhanna** [comment]
Okay I think that # 2 is the best like u said bc that’s the way I have tried before… like long ago when I was helping my cousin make a website for stuff…(I just was trying to learn what he was doing)

also why did u add me to the developers and then remove me.. like it’s cool… I can be a developer Idrc rn cuz I haven’t done anything and I should but my parents want me doing other things away from my computer for thanksgiving break so I’m unable to sorry

>

**Comment by grimsteel** [comment]
> Okay I think that # 2 is the best

Thanks

> also why did u add me to the developers and then remove me

I don't want to seem rude or anything but you haven't committed to the repo at all yet, and being on the developers team gives you full write access. I wanted you to have the info in the team, but I wanted to hold off on the perms ***for now***. I added developing info to the README if you want to see that

Note that you don't have to be on the developers team to be a contributer - being on it just shows that you have a reasonable experience with the Vocabustudy code

**Comment by ShreyanKhanna** [comment]
> > Okay I think that # 2 is the best
> 
> Thanks
> 
> > also why did u add me to the developers and then remove me
> 
> I don't want to seem rude or anything but you haven't committed to the repo at all yet, and being on the developers team gives you full write access. I wanted you to have the info in the team, but I wanted to hold off on the perms _**for now**_. I added developing info to the README if you want to see that
> 
> Note that you don't have to be on the developers team to be a contributer - being on it just shows that you have a reasonable experience with the Vocabustudy code

Makes sense cuz like u said I haven’t done anything so I only want it if I do things and I need it… plus I’m kinda brainstorming and when I’m like boom we need to do this… it just doesn’t seem good and I’m kinda scared that it is a bad idea and don’t put an issue in

**Comment by grimsteel** [comment]
No worries - if you want a place to put brainstormed ideas that may not warrant a full issue, you could use discussions

**Comment by ShreyanKhanna** [comment]
Yea sound good

**Comment by IMGROOT2** [comment]
> There are three possible things we could do:
> 
> 1. Use Firestore and generate a JSON stored in Cloud Storage
> 2. Do it all in Cloud Storage (my preferred option)
> 3. Do it all in Firestore (I think this is what you are saying?)
> 
> The thing about option 3 is that it would be harder to cache than Cloud Storage. In addition, there are two possible options for that: `users` collection:

I was thinking option 3.1 lol. if you're comfortable with cloud storage, then let's do that.

**Comment by ShreyanKhanna** [comment]
> > There are three possible things we could do:
> > 
> > 1. Use Firestore and generate a JSON stored in Cloud Storage
> > 2. Do it all in Cloud Storage (my preferred option)
> > 3. Do it all in Firestore (I think this is what you are saying?)
> > 
> > The thing about option 3 is that it would be harder to cache than Cloud Storage. In addition, there are two possible options for that: `users` collection:
> 
> I was thinking option 3.1 lol. if you're comfortable with cloud storage, then let's do that.

That would also work but hear me out and I could be wrong but isn’t option 2 simpler?

**Comment by ShreyanKhanna** [comment]
And more versatile?

**Comment by IMGROOT2** [comment]
option 2 is cloud storage lol. we're on the same page

**Comment by ShreyanKhanna** [comment]
Alr

**Comment by IMGROOT2** [comment]
This will now be 10 times easier with Bulma tags

**Comment by PrakmO** [comment]
nice

**Comment by ShreyanKhanna** [comment]
> This will now be 10 times easier with Bulma tags

perfect

**Comment by grimsteel** [comment]
Handled by the custom `roles` auth property (#291)
