### ISSUE TITLE
Friend and Follow Feature as well as Chat and Competitive/Duel features 

### ISSUE THREAD

**Issue by ShreyanKhanna** [For-0/vocabustudy#241]
Okay so this may be a dumb feature… but I was thinking about like friending users and following them as well.

the follow button could be used to know when a user has made a new set.

While the friend festure could be used like the follow but it would be two wayed meaning that both people must follow each other to be able to become friends on vocabustudy.This will also allow you to chat with one another … useful if the other person doesn’t have a phone or discord.

Lastly, the friend feature could be useful with another feature… the competition/ duel feature which make another fun way to practice vocab with a friend(you compete against them). 

Please let me know if any changes should be added to this.

**Comment by IMGROOT2** [comment]
Chatting/Competition/Duel all require a ton of server reads and a lot of server power, which we don't have at all

**Comment by ShreyanKhanna** [comment]
Alr but what abt the other parts

**Comment by ShreyanKhanna** [comment]
I are we planning on getting more? In the future

**Comment by grimsteel** [comment]
This might get Vocabustudy blocked as it would be a "social" site

**Comment by DG3QRT1** [comment]
Yes
That's what I told him in LA
