### ISSUE TITLE
go.vocabustudy.org/ is an invalid Dynamic link

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#242]
I think that https://go.vocabustudy.org/ should redirect to a one-page directory of all “go.” links.

**Comment by ShreyanKhanna** [comment]
Yea but what are go links

**Comment by IMGROOT2** [comment]
Are you watching this repo? You should because go links were talked about a week ago

**Comment by ShreyanKhanna** [comment]
Yes I am

**Comment by ShreyanKhanna** [comment]
Alr I’ll. Look at those

**Comment by IMGROOT2** [comment]
cool

**Comment by ShreyanKhanna** [comment]
I did t see it but it’s fine.. I’ll ask siddhant later

**Comment by IMGROOT2** [comment]
Go. Links are like shortcuts to stuff. For example, try go.vocabustudy.org/discord or /nightly

**Comment by grimsteel** [comment]
This isn't possible with the current dynamic links setup - it's also consistent with things like https://forms.gle
