### ISSUE TITLE
Redirect www. to non-www.

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#243]
Going to https://www.nightly.vocabustudy.org should lead to https://nightly.vocabustudy.org

Just an .htaccess file should take care of it.

**Comment by IMGROOT2** [comment]
A similar thing needs to be done to all go. links

**Comment by grimsteel** [comment]
> Just an .htaccess file should take care of it.

I wish this was an Apache server... (Firebase Hosting is better than things like Wordpress but still there's little customizability. Also I'm not sure if htaccess is an apache thing? I always confuse Apache and Nginx)

Also as a side not I've never seen www.subdomain.domain.tld before...

**Comment by IMGROOT2** [comment]
> I wish this was an Apache server... (Firebase Hosting is better than things like Wordpress but still there's little customizability. Also I'm not sure if htaccess is an apache thing? I always confuse Apache and Nginx)

.htaccess is apache, MB. but, firebase.json supports redirects and stuff, I'll check it out in docs.

> Also as a side note I've never seen [www.subdomain.domain.tld](http://www.subdomain.domain.tld/) before...

that's because they're always redirected. if you want a working www.subdomain.domain.tld, try https://www.drive.google.com/ which is a pretty popular one lol

**Comment by grimsteel** [comment]
Interesting...
I'm configuring this directly in DNS so www.go should already work (certificate is on the way!)

**Comment by IMGROOT2** [comment]
cool!
