### ISSUE TITLE
Bugs/ Feedback from integrated into vocabustudy.org

### ISSUE THREAD

**Issue by ShreyanKhanna** [For-0/vocabustudy#248]
Okay, so I wanted to know if it is possible to just have a feedback/ bug reporting from the website itself, then you could just click the button and it will take u to the page in vocabustudy and you can fill it out there, this might help when/ if we want to move leaderboard to the website itself.

The reason that this would make sense is that google forms make it look less professional and moving it to the page will make it look better and could have better functionality. And i don't have a problem working on this if we want to do this.

**Comment by IMGROOT2** [comment]
what if we temporarily just embed the google form into the website?

**Comment by ShreyanKhanna** [comment]
if we could have done that why haven't we??? like the google sheets working but then glitched I think... and then we stopped using it.
But al I'm saying is that it would look clearer if we added it.

**Comment by grimsteel** [comment]
> like the google sheets working but then glitched I think... and then we stopped using it.

What?? I use it every day! I generally keep issues reported at school over there

> if we could have done that why haven't we???

You can do it if you want to

**Comment by IMGROOT2** [comment]
> if we could have done that why haven't we??? like the google sheets working but then glitched I think... and then we stopped using it.
> But al I'm saying is that it would look clearer if we added it.

Nobody wants to create a whole page for embedding. Also @grimsteel uses the sheet every day

**Comment by grimsteel** [comment]
The easiest way to make a form would be with "Pageclip" (included in the pack) but it would be blocked at school. Also there's a maximum of 20000 submissions total. It would probably be more efficient to do some from of firestore stuff.
Or, we could beg and plead and do 🥺 to get Github unblocked, and set up [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by ShreyanKhanna** [comment]
> The easiest way to make a form would be with "Pageclip" (included in the pack) but it would be blocked at school. Also there's a maximum of 20000 submissions total. It would probably be more efficient to do some from of firestore stuff.
> Or, we could beg and plead and do 🥺 to get Github unblocked, and set up [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

I can beg

**Comment by IMGROOT2** [comment]
change.org?

**Comment by IMGROOT2** [comment]
should i set up one for fun

**Comment by grimsteel** [comment]
Sure...
That might actually work
I'll get some teachers to sign it (or whatever it's called) too

**Comment by IMGROOT2** [comment]
i have a thing for marketing 
here we go

**Comment by ShreyanKhanna** [comment]
Alr go ahead

**Comment by ShreyanKhanna** [comment]
> i have a thing for marketing
> here we go

Here we go - Mario 1998

**Comment by PrakmO** [comment]
> > if we could have done that why haven't we??? like the google sheets working but then glitched I think... and then we stopped using it.
> > But al I'm saying is that it would look clearer if we added it.
> 
> Nobody wants to create a whole page for embedding. Also @grimsteel uses the sheet every day

we all use it

**Comment by PrakmO** [comment]
> if we could have done that why haven't we??? like the google sheets working but then glitched I think... and then we stopped using it. But al I'm saying is that it would look clearer if we added it.

It still works.... I used it today

**Comment by PrakmO** [comment]
@ShreyanKhanna Happy birthda

**Comment by PrakmO** [comment]
I did it
