### ISSUE TITLE
Link Help Center on Vocabustudy

### ISSUE THREAD

**Issue by Nikhilatvocabustudy** [For-0/vocabustudy#253]
I am asking for permission to create a page (similar to the pages we have for discord and credits) for our help center. I am not sure how advanced our help  center is, and whether or not we even can do this

**Comment by IMGROOT2** [comment]
I don't think I can give an executive decision here, but I'd say that the help center is much more important than the links in the footer, so keeping it at the top makes it easier to access. Also, could https://help.vocabustudy.org be an avenue we take with the help center?

**Comment by grimsteel** [comment]
I agree - the top gives it better visibility and also makes the footer less bloated

**Comment by grimsteel** [comment]
> Also, could https://help.vocabustudy.org/ be an avenue we take with the help center?

I can set up a redirect rn - help.vocabustudy.org will redirect to the current help center page

**Comment by Nikhilatvocabustudy** [comment]
Currently it is not linked period, do you want me to do that

**Comment by grimsteel** [comment]
![image](https://user-images.githubusercontent.com/115331356/204960610-c89eba39-930b-4c0a-914d-30d0b5dd6f44.png)
