### ISSUE TITLE
Help Center: Articles QOL

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#264]
# Help Center QOL Tasklist
### Let's get Bulma released first before we start making major edits. 

- [ ] Add More Articles! We need a few more for the "Featured Articles" section to look good.
- [ ] Fix grammar (just run the whole thing through Grammarly, basically). For example:
![image](https://user-images.githubusercontent.com/116324098/208511474-233109ce-a1b4-4af6-822c-ce8038bf82ea.png)
I don't think we're talking about the Pokemon Mew here... lol
- [ ] Make links clickable. **These links should open in a new tab so you can easily refer back to the Help Center.** 
![image](https://user-images.githubusercontent.com/116324098/208511809-99ced524-36a6-4aac-8ded-33307adf2474.png)
- [ ] Add inline icons to easier follow directions: 
![image](https://user-images.githubusercontent.com/116324098/208512479-89c85af4-4316-4f07-b415-f0e4cb238326.png)
In this, we would replace "add" with an in-line non-clickable button of the actual add button, a.k.a:
![image](https://user-images.githubusercontent.com/116324098/208513503-d36dcf02-b6c8-4389-9c23-62cb80f58776.png)
- [ ] Typography update:
![image](https://user-images.githubusercontent.com/116324098/208512771-ac2f3b82-0041-482d-82bd-142797dda134.png)
Let's make this look more cohesive, and we should separate the steps and the guidelines more clearly. Maybe a Bulma Notification that cannot be closed for the guidelines, sort of like this:
![image](https://user-images.githubusercontent.com/116324098/208513116-37ef0351-6920-42f3-a793-39d095d45a96.png)

After this, the Help Center will look even better and be more helpful to all Vocabustudy users. I'll set the deadline to 2.0.0, we can change this if necessary.

**Comment by grimsteel** [comment]
I have many problems with the current help center

**Comment by grimsteel** [comment]
Mainly the spelling

**Comment by IMGROOT2** [comment]
Yes, we'll fix them with this issue.

**Comment by IMGROOT2** [comment]
Incredibly outdated, closing since new Help Center articles are not yet written for the new Vocabustudy
