### ISSUE TITLE
Link Sister Sites

### ISSUE THREAD

**Issue by Nikhilatvocabustudy** [For-0/vocabustudy#270]
If you guys think it's a good idea, can we link the other sites (simple text editor, staarsap) on vocabustudy either now or at some point in the future. IF you guys say yes, I'll do it

**Comment by IMGROOT2** [comment]
Like a webring?

**Comment by grimsteel** [comment]
I think it's just a better idea to keep everything on the FZO website

**Comment by grimsteel** [comment]
Vocabustudy is meant as a distraction free studying website
