### ISSUE TITLE
 ignore-user-hue needs to be added to Sign in with Google (and probably Onetap too)

### ISSUE THREAD

**Issue by IMGROOT2** [For-0/vocabustudy#280]
![image](https://user-images.githubusercontent.com/116324098/216831931-570c8492-4d3f-43af-8c38-3e401ac7535c.png)

Add the `ignore-user-hue` class to the Sign in with Google button.

**Comment by grimsteel** [comment]
this is probably a bug with browsers because why on earth is the filter applying to the iframe??
