### ISSUE TITLE
All sets not showing up

### ISSUE THREAD

**Issue by Nikhilatvocabustudy** [For-0/vocabustudy#290]
I'll keep it brief since I've already explained this to Siddhant
Esentially, When I go to my sets, not all of my sets will show up, even after clicking "load more"

However, when I go to saved sets (which includes some of my sets) it shows sets made by me, that are public, and do not show up under "my sets"

**Comment by grimsteel** [comment]
This is because the pagination uses startAfter 0 for likes and because likes are descending, after you click load more (on any page that has pagination :skull:) it will skip all the sets until the ones that have 0 likes

**Comment by Nikhilatvocabustudy** [comment]
Ah that's pretty interesting
