### ISSUE TITLE
MCQs disappear in test mode

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#296]
**Describe the bug**
Multiple choice and true/false questions disappear in test mode when you click "Submit", and do not get graded.

**To Reproduce**
1. Go to https://vocabustudy.org/set/Kazi7LfCbcX1mwSwoRfU/test/
2. Set max questions to 1
3. Uncheck everything except multiple choice
4. Pick an option on the single MCQ
5. Click submit
6. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f6266431-8702-4529-89da-6bd16ae9d643)

**Additional context**
why did I fill this whole template out if I'm going to fix it myself

**Comment by IMGROOT2** [comment]
Thank you for your bug report, @grimsteel! The Vocabustudy team will handle this shortly. Have a good day!

lol

**Comment by grimsteel** [comment]
Thank you for your quick response, @IMGROOT2! I look forward to seeing this issue resolved.
