### ISSUE TITLE
Saving Sets Feature

### ISSUE THREAD

**Issue by grimsteel** [For-0/vocabustudy#3]
Once there are a lot of sets, not needed yet

**Comment by DG3QRT1** [comment]
Isn't this done?

**Comment by grimsteel** [comment]
Saving sets as in downloading them for offline use
Liking sets is for online use, and it can only be used when logged in
Saving sets can be used when logged out and is not synced to your account

**Comment by ShreyanKhanna** [comment]
why is it not synced to the account?; like wouldn't it be easier if it was linked to the account, if everything is, then we can fix and find things easily, right?

**Comment by grimsteel** [comment]
It's way easier for me if it's stored locally
Also why would it be easier to fix bugs if it was linked to the account?

**Comment by ShreyanKhanna** [comment]
Nvm had two train of thoughts so
